// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package diego.ufu.workloadoutput.main;

public class ExperimentBuilder extends ExperimentBuilderBase<ExperimentBuilder> {

	public static ExperimentBuilder experiment() {
		return new ExperimentBuilder();
	}

	public ExperimentBuilder() {
		super(new Experiment());
	}

	public Experiment build() {
		return getInstance();
	}
}

class ExperimentBuilderBase<GeneratorT extends ExperimentBuilderBase<GeneratorT>> {
	private Experiment instance;

	protected ExperimentBuilderBase(Experiment aInstance) {
		instance = aInstance;
	}

	protected Experiment getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withMallocFileName(String aValue) {
		instance.setMallocFileName(aValue);
		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withFreeFileName(String aValue) {
		instance.setFreeFileName(aValue);
		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPath(String aValue) {
		instance.setPath(aValue);
		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withOutputFilePath(String aValue) {
		instance.setOutputFile(aValue);
		return (GeneratorT) this;
	}
}
